version: '3.8'

services:
  my-app:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_DB_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_DB_PWD=${MONGO_ADMIN_PASS}
    volumes:
      - .:/src
    networks:
      - mongodb-network

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASS}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL= mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASS}@mongodb:27017/
    depends_on:
      - mongodb
    volumes:
      - mongodb-express-data:/data/db
    networks:
      - mongodb-network

volumes:
  mongodb-data:
  mongodb-express-data:

networks:
  mongodb-network:
    driver: bridge